using System;
using System.Collections.Generic;
using System.Deployment.Internal;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Properties
{
    class Program
    {
        static void Main1(string[] args)
        {
            //Program p = new Program();
            //p.Display();
            Class1 o = new Class1();
            o.i = ++o.i+o.i++ - o.i-- - --o.i;
            //o.x

            o.Setx(1000);
            Console.WriteLine(o.Getx());
            Console.ReadLine();

        }
        //public void Display()
        //{
        //    Console.WriteLine("Display");
        //}
        static void Main(string[] args)
        {
            //Program p = new Program();
            //p.Display();
            Class2 o = new Class2();
            o.X = 1000;
            Console.WriteLine(o.X);//get 
            //o.P1 = "a";
            o.P4 = 10;//set
            Console.WriteLine(o.P4);//get

            Console.ReadLine();

        }
    }
    public class Class1
    {
        public int i; //field //by default i=0;//by default private 
        private int x;

        public void Setx(int VALUE)
        {
            if (VALUE < 100) 
            {
                x = VALUE;

            }
            else
            {
                Console.WriteLine("Invalid value for x");
            }

        }
        public int Getx()
        {
            return x;
        }

    }
    public class Class2
    {
        private int x;
        public int X
        {
            set
            {
                //value is the right hand side of o.X-10;
                if (value < 100)
                {
                    x = value;

                }
                else
                {
                    Console.WriteLine("Invalid Value for x");

                }
            }
            get
            {
                return x;
            }

        }
        private string p1 = "abc";
        public string P1 //readonly property
        {
            get
            {
                return p1;
            }
        }

        private int p2;
        public int P2
        {
            set
            {
                p2 = value;
            }
            get
            {
                return p2;
            }
        }
        public int P3;//field/variabe

        //Automatic Property  - use it when there are no validate x
        //get and set code is generated by compiler 
        //private variable is generated y compiler 
        public int P4{get; set;}

        private int p5;

        //only one of get/set can have a property accessor 
        //you can only reduce access, not increase it 

        //less
        //public 
        //protected internal

        //protected /internal  are same level 
        //private protected
        //private 
        //more 


        public int P5
        {
            private set //property accessor
            {
                p5 = value;
            }
            get
            {
                return p5;
            }
        }



    }
}
 
